
title: HealTAC 2024 
email:
description: >- # this means to ignore newlines until "baseurl:"
  HEALTHCARE TEXT ANALYTICS CONFERENCE 2024
  Lancaster University, JUNE 14-16, 2024
# url: "https://conf-nlpaics-2024.github.io"
baseurl: "conf-nlpaics-2024"
twitter_username: username
github_username: dml2611
search: true

accent_image:          assets/img/lake_1.jpg
accent_color:          rgb(79,177,186)
theme_color:           rgb(25,55,71)

google_fonts:          Roboto+Slab:700|Noto+Sans:400,400i,700,700i
font:                  Noto Sans, Helvetica, Arial, sans-serif
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif
font-code:             ui-monospace, Menlo, Monaco, "Cascadia Mono", "Segoe UI Mono", "Roboto Mono", "Oxygen Mono", "Ubuntu Monospace", "Source Code Pro", "Fira Mono", "Droid Sans Mono", "Courier New", monospace;

hydejack:
  post_addons:         [about, newsletter, related, random, comments]
  project_addons:      [about, newsletter, other, comments]

  no_mark_external:    false
  no_push_state:       false
  no_drawer:           false
  no_navbar:           false
  no_search:           false
  no_inline_css:       false
  no_page_style:       false
  no_break_layout:     true
  no_toc:              false
  no_third_column:     false
  no_large_headings:   false
  no_structured_data:  false
  no_theme_color:      false
  no_breadcrumbs:      false

  use_lsi:             true
  cookies_banner:      true
  advertise:           true
  hide_dates:          false
  hide_last_modified:  false

  dark_mode:
    always:            false
    dynamic:           true
    sunrise:           6
    sunset:            18
    icon:              true

  offline:
    enabled:           false
    cache_version:     1
    precache_assets:
      - /assets/img/swipe.svg

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true
  
relative_links:
  enabled:     true
  collections: true

titles_from_headings:
  strip_title:         true
  collections:         true

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed
  
# Build settings
# remote_theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v9
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-relative-links
  
menu:
  - title: Home
    url:   /home/
  - title: Programme
    url:   /programme/
  - title: Registration
    url:   /registration/
  - title: Venue
    url:   /venue/
  - title: Keynote Speakers
    url:   /keynote-speakers/
  - title: Committees
    url:   /committees/
  - title: Sponsors
    url:   /sponsors/
  - title: Contact Us
    url:   /contact/

slideshow:
  - /assets/img/image_1.jpg
  - /assets/img/image_2.jpg
  - /assets/img/image_3.jpg
  - /assets/img/image_4.jpg
  - /assets/img/Lake-District-1.jpg
  - /assets/img/Lake District-2.jpg
  - /assets/img/Ullswater.jpg

slideshow-venue:
  - /assets/img/venue_1.jpg
  - /assets/img/venue_2.jpg
  - /assets/img/venue_3.jpg

left-tab:
  - title: Announcements
    url: /announcements/
  - title: Important Dates
    url:   /dates/
  - title: Calls
    url:   /calls/
  - title: Submissions
    url:   /submissions/
  - title:  Submission Topics
    url:   /submission-topics/
  
